### ISSUE TITLE
Suggestion for Organizing Configurable Files

### ISSUE THREAD

**Issue by rafaelvieiras** [vinicioslc/tinfoil-hat#16]
Congratulations on the project! I was looking to reduce the **3GB** 💀 that NUT was consuming in my homelab, and your project was the perfect solution.

I would like to suggest an improvement: 
Instead of saving the `shop.json` and `shop.tfl` files in the `/games` folder, we could use a `/config` folder. 

This would even be useful for storing other data in the future. Thus, the user can map the container folder to the folder he wants, avoiding conflicts with established standards, such as RetroArch, for those who organize ROMs in separate folders per console.

😄

**Comment by vinicioslc** [comment]
Ok,
I just released a new update that don't create theses static files `shop.json` and `shop.tfl` at `/games` folder avoiding change users files layout.

Now the server fake these `shop.*` files at index.html generating (on request) an "a fake `index.html`" since it is only needed to the tinfoil to discover the `shop.*` files 

no more file system based index.html... 

The new docker release available: 

[![Create and publish tinfoil-hat image](https://github.com/vinicioslc/tinfoil-hat/actions/workflows/docker.yml/badge.svg)](https://github.com/vinicioslc/tinfoil-hat/actions/workflows/docker.yml)

[Github Actions](https://github.com/vinicioslc/tinfoil-hat/actions/runs/9845744335)

**Comment by vinicioslc** [comment]
@rafaelvieiras please test and inform if its ok to close this issue

**Comment by rafaelvieiras** [comment]
@vinicioslc 
I tried it here! Everything works great!

My question, is shop.* no longer saved? Or if it is, I would like to map the directory in my Docker.

I use https://unraid.net/ on my Homelab, and it has a cache disk strategy, stored on an NVMe SSD, which differs from the disks I keep my ROMs on, which is the HDD.

So I always map the docker data folders (like databese sqlite files) to my SSDs, for reasons of reading and writing performance, in addition to conserving the HDDs for sporadic and only necessary use.

**Comment by vinicioslc** [comment]
hi, @rafaelvieiras 

Q: shop.* no longer saved?
R: nop

briefly: 

However, the “tinfoil-hat” system currently lists all files in the “./games” folder. By doing so, it avoids the need to keep any information in memory. This approach contributes to low resource consumption when the system is idle.

With that in mind, I don't think you need to change nothing, this could lead to some wait time in "tinfoil switch app" because slow hdd speed but its tolerable
