### ISSUE TITLE
no games showing

### ISSUE THREAD

**Issue by dnsBlah** [vinicioslc/tinfoil-hat#6]
I'd like to applaud for how easy it is set it up with node!
nsp, xci files parsed perfectly fine in shop files:
  tinfoil-hat:request IN-> '/shop.tfl' +8ms
  tinfoil-hat total game/save files found: 18 +11ms
  tinfoil-hat total directories found: 0 +0ms

but none are showing in tinfoil under "New Games" or such.

`...
{"url":"../The%20Legend%20of%20Zelda%20Tears%20of%20the%20Kingdom%20%5B0100F2C0115B6800%5D%5Bv131072%5D%5BUS%5D%28nsw2u.com%29.nsp","size":332747088},{"url":"../YouTube%20%5B05003A400C3DA000%5D%5Bv262144%5D%5BBase%5D.nsp","size":72389836}],"directories":[],"success":"The Server Works!!"}`

**Comment by ablakers** [comment]
Can you see the games in https://github.com/a1ex4/ownfoil ? I had been on ownfoil where I could see the games but save backups didn't write properly, moved over to tinfoil-hat and had the opposite - backing up saves works without a hitch but tinfoil-hat isn't detecting the games, shop.tfl and .json are blank.
I'm on a Windows host using docker compose fwiw

**Comment by vinicioslc** [comment]
@ablakers and @dnsBlah probably your folder structure isnt grouped by dir check how its structured and try follow this pattern of folder naming 
![image](https://github.com/vinicioslc/tinfoil-hat/assets/10997022/d6e34414-9ed2-4df9-bd3d-1b5f4441c3fb)

**Comment by ablakers** [comment]
The files I had were just flat at the root of my games directory, I moved in another subfolder with the same structure as your example and restarted tinfoil-hat but no change. All the filenames have the same structure too.

**Comment by vinicioslc** [comment]
you mounted the container volume correctly ?
i need some debug info 
what its the console logging output ?
the tinfoilhat is saying that found some file ? if not is your container settings

**Comment by ablakers** [comment]
It's not saying it's found files, but it can create the shop.json and shop.tfl files if they don't already exist, and it can still show those files in Tinfoil and on the web interface (also the .jsonc file from when I tried docker compose with the yml inside the games directory

[tinfoil-hat.log](https://github.com/vinicioslc/tinfoil-hat/files/12421256/tinfoil-hat.log)

**Comment by vinicioslc** [comment]
@ablakers you shouldn't execute the docker-compose up -d inside /games folder, it should be at parent folder tinfoilhat/ or something with the /games folder inside.
Beyond this, inside the logs he is saying that jsonc file are wrong you changed something ? if yes you should pass thought some linter or formatter anyway ..

**Comment by ablakers** [comment]
I didn't originally have the .yml there in the same directory, just tried running it from there to see if it made a difference. I've now commented out the line about the shop_template.jsonc line of the .yml (it wasn't commented out on the file on the repo so I thought it would just do nothing with a blank file) - the log now shows it's found game/save files and directories, and the numbers match what's in there, but it's still only displaying the .json and .tfl in the shop and web interface.

EDIT: Just added some more files to the directory and although the web interface isn't showing the files or directories, things I haven't installed are showing in the New Games/New DLC sections of Tinfoil unlike @dnsBlah , which I now see is expected behavior - apologies, ownfoil had still shown the nsps in file browser so I didn't know. Should the files be shown in the web interface though? Still only seeing shop files there.  Also my saves in `Saves/Tinfoil` show in the Shared Saves section, but not the `Saves/JKSV` ones, I'm new to Tinfoil so is that expected behavior?)

**Comment by dnsBlah** [comment]
> @ablakers and @dnsBlah probably your folder structure isnt grouped by dir check how its structured and try follow this pattern of folder naming
> ![image](https://user-images.githubusercontent.com/10997022/262714028-d6e34414-9ed2-4df9-bd3d-1b5f4441c3fb.png)

Yes sir! That was it :)

**Comment by vinicioslc** [comment]
@ablakers about not showing at web interface its right!
the server not show for browser users, this is a workaround for TinfoilApp Switch limitation it does not render any games if the index.html page displays many game entries like +50 entries, preventing the games from being loaded, maybe at some point I will test if this has already been fixed by Tinfoil Team


> I didn't originally have the .yml there in the same directory, just tried running it from there to see if it made a difference. I've now commented out the line about the shop_template.jsonc line of the .yml (it wasn't commented out on the file on the repo so I thought it would just do nothing with a blank file) - the log now shows it's found game/save files and directories, and the numbers match what's in there, but it's still only displaying the .json and .tfl in the shop and web interface.

About saves 
Tinfoil app has some limitation that i dont know, (the code isnt open source) if you discover if is possible or how to show JKSV .zip backup files for tinfoil restore, maybe I could adjust it so that allow to be displayed, but like for me and you it only works for the listing for tinfoil's made backups

>EDIT: Just added some more files to the directory and although the web interface isn't showing the files or directories, things I haven't installed are showing in the New Games/New DLC sections of Tinfoil unlike @dnsBlah , which I now see is expected behavior - apologies, ownfoil had still shown the nsps in file browser so I didn't know. Should the files be shown in the web interface though? Still only seeing shop files there. Also my saves in Saves/Tinfoil show in the Shared Saves section, but not the Saves/JKSV ones, I'm new to Tinfoil so is that expected behavior?)

**Comment by Reaster0** [comment]
hey, i have a similar issue, i don't see any files on the webserver, but using ownfoil there's no issue,
here is the content of my dir:
<img width="350" alt="Capture d’écran 2023-08-27 à 18 35 03" src="https://github.com/vinicioslc/tinfoil-hat/assets/73885131/b90b4bd3-a86c-44bd-b22a-3bcbd45d6f95">

and here is the content of my docker-compose :
<img width="836" alt="Capture d’écran 2023-08-27 à 18 37 21" src="https://github.com/vinicioslc/tinfoil-hat/assets/73885131/19ba1646-94b1-4b2c-8a52-e4cd5904bac2">

**Comment by dnsBlah** [comment]
> hey, i have a similar issue, i don't see any files on the webserver, but using ownfoil there's no issue, here is the content of my dir: <img alt="Capture d’écran 2023-08-27 à 18 35 03" width="350" src="https://user-images.githubusercontent.com/73885131/263542098-b90b4bd3-a86c-44bd-b22a-3bcbd45d6f95.png">
> 
> and here is the content of my docker-compose : <img alt="Capture d’écran 2023-08-27 à 18 37 21" width="836" src="https://user-images.githubusercontent.com/73885131/263542131-19ba1646-94b1-4b2c-8a52-e4cd5904bac2.png">

Put your dumps in subfolders per game

**Comment by Reaster0** [comment]
yeah you're right, i've used https://github.com/giwty/switch-library-manager
to manage my releases and it put every release into the directory so now i don't have any issues

**Comment by TerrorSource** [comment]
Got the same issue.
Running tinfoil-hat on my Synology in Docker.

games are seperated folders in /games/
Docker works.
IP:99/shop.json = shows files are found within their own folders
repo/shop added in tinfoil, welcome message is shown (twice)
tab "new games" is missing in tinfoil

when i add the repo in tinfoil with path "/shop.json" i see the files in the repo, when i download them i need to buy them from the eShop.
